const args = process.argv.slice(2);

// Проверяем наличие аргументов
if (args.length === 0) {
    console.log('Пожалуйста, укажите аргумент при запуске скрипта.');
    process.exit(1);
}

// Получаем первый аргумент
const argument = args[0];

// Определяем функции для каждого аргумента
const functions = {
    init: () => {
        const sqlite3 = require('sqlite3').verbose();
        const db = new sqlite3.Database('database.db');

        db.run(`CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, brand_original TEXT NOT NULL, brand_translation TEXT NOT NULL, type TEXT DEFAULT NULL, title_original TEXT NOT NULL, title_translation TEXT, description TEXT DEFAULT NULL, pictures TEXT DEFAULT NULL, volume TEXT, price REAL, price_factor INTEGER, amount INTEGER, weight INTEGER, 'exists' INTEGER, discount INTEGER NOT NULL DEFAULT 0 CHECK(discount >= 0 AND discount <= 100))`);
        db.run(`CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, user INTEGER REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, phone_number TEXT NOT NULL, products JSONB NOT NULL, region TEXT NOT NULL, address TEXT NOT NULL, comment TEXT, status INTEGER NOT NULL)`);
        db.run(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, phone_number TEXT NULL, password TEXT NOT NULL, admin BOOLEAN NOT NULL DEFAULT 0, reg_date DATETIME, log_date DATETIME)`);
        db.run(`CREATE TABLE IF NOT EXISTS favorites (user INTEGER, product INTEGER, FOREIGN KEY(user) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(product) REFERENCES products(id) ON DELETE CASCADE)`);
        db.run(`CREATE TABLE IF NOT EXISTS reviews (user INTEGER NOT NULL REFERENCES users(id) ON DELETE SET NULL, grade INTEGER CHECK (grade BETWEEN 1 AND 5), comment TEXT DEFAULT NULL)`);
        db.run('PRAGMA encoding = "UTF-8"');
    },
    write: () => {
        const sqlite3 = require('sqlite3').verbose();
        const db = new sqlite3.Database('database.db');

        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, pictures, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Babylove', 'Бейбілав', '', 'Wundschutzcreme ultra sensitive', 'Крем для захисту ран (Ультрачутливий)', '["https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1651745690/products/pim/4058172434273-3165514/babylove-wundschutzcreme-ultra-sensitive","https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1663057169/products/pim/4058172434273-2563438/babylove-wundschutzcreme-ultra-sensitive"]', '150 мл', '1.95', '35', '10', '', '1']);
    /*    db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea MEN', 'Балеа МЕН', '', 'Deo Zerstäuber Fresh', 'Дезодорант-спрей (Cвіжість)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1686750404/products/pim/4058172754876-3333772/balea-men-deo-zerstaeuber-fresh', '75 мл', '1.35', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Dusche Hawaiian Dream', 'Гель для душу (Гавайська мрія)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1683886478/products/pim/4066447342444-3793312/balea-dusche-hawaiian-dream', '300 мл', '0.55', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Haarlack windresistent', 'Лак для волосся', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1591908381/products/pim/4058172320545-2049992/balea-haarlack-windresistent', '300 мл', '1.55', '35', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Dontodent', 'Донтодент', '', 'Mundspülung sensitive intensiv Schutz', 'Ополіскувач для рота, чутливий (Інтенсивний захист)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1656688475/products/pim/4058172925931-2968499/dontodent-mundspuelung-sensitive-intensiv-schutz', '500 мл', '0.85', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Shampoo Natural Beauty mit Bio-Avocadoöl und Mangobutter', 'Шампунь з органічною олією авокадо та маслом манго', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1686729603/products/pim/4066447238877-3876843/balea-shampoo-natural-beauty-mit-bio-avocadooel-und-mangobutter', '400 мл', '1.55', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Shampoo Natural Beauty Locken', 'Шампунь для локонов', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1686209241/products/pim/4066447239133-3876860/balea-natural-beauty-shampoo-locken', '400 мл', '1.55', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Trockenshampoo Classic', 'Сухий шампунь (Класичний)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1671030857/products/pim/4058172784378-3135339/balea-trockenshampoo-classic', '200 мл', '1.95', '22', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Cremedusche Sensitive', 'Крем для душу (Чутливий)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1687955381/products/pim/4066447234619-3734943/balea-cremedusche-sensitive', '300 мл', '0.55', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea MED', 'Балеа МЕД', '', 'seifenfreie Waschlotion, hautneutral, Nachfüllpack', 'Лосьйон для вмивання, нейтральний для шкіри, наповнювач', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1688549102/products/pim/4066447237948-4059821/balea-med-seifenfreie-waschlotion-hautneutral-nachfuellpack', '500 мл', '0.95', '22', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Kinder Waschschaum Underwater Friends', 'Дитяча пінка для вмивання (Підводні друзі)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1667514527/products/pim/4058172778742-2970905/balea-kinder-waschschaum-underwater-friends', '250 мл', '0.95', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Seifenstück sensitive mit Aloe-Vera-Extrakt', 'Крем-мило, Savona (Чутливе, з екстрактом алое вера)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1665752676/products/pim/4058172483394-2074687/balea-seifenstueck-sensitive-mit-aloe-vera-extrakt', '150 мл', '0.45', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea MED', 'Балеа МЕД', '', 'Handcreme hautneutral mit Allantoin', 'Крем для рук (Нейтральний для шкіри, з алантоїном)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1673970870/products/pim/4066447110159-3261262/balea-med-handcreme-hautneutral-mit-allantoin', '100 мл', '1.25', '22', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Alverde NATURKOSMETIK', 'Алверде НАТУРКОСМЕТіК', '', 'Shampoo Family Bio-Malve, Bio-Brombeere', 'Шампунь, сімейний (Органічна мальва, органічна ожина)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1688627861/products/pim/4066447235319-4054728/alverde-naturkosmetik-shampoo-family-bio-malve-bio-brombeere', '300 мл', '2.65', '35', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Deospray Soft Flower', 'Дезодорант-спрей', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1686846012/products/pim/4058172813979-3392452/balea-deospray-soft-flower', '200 мл', '0.95', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Mivolis', 'Міволіс', '', 'Mama Folsäure + DHA, Tabletten 30 St. + Weichkapseln', 'Mama Folsäure + DHA, таблетки (30 шт.) + мякі капсули (30 шт.)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1688119496/products/pim/4066447416565-3965479/mivolis-mama-folsaeure-dha-tabletten-30-st-weichkapseln-30-st', '', '4.25', '35', '10', '41 г', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Mivolis', 'Міволіс', '', 'Immun Fit Brausetabletten', 'Иммун Фит шипучие таблетки', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1688654102/products/pim/4066447248746-3648999/mivolis-immun-fit-brausetabletten-20-st', '', '1.55', '35', '10', '80 г', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Balea', 'Балеа', '', 'Haarlack Ultra Power', 'Лак для волос (Ультра мощность)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1651369550/products/pim/4058172619052-3271170/balea-haarlack-ultra-power', '300 мл', '1.15', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Dontodent', 'Донтодент', '', 'Zahnseide antibakteriell', 'Зубна нитка (Антибактеріальна)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1658310032/products/pim/4058172063176-1646255/dontodent-zahnseide-antibakteriell', '100 м', '0.85', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Babylove', 'Бейбилав', '', 'Baby Waschgel Kopf bis Fuß Sensitive', 'Дитячий гель для вмивання (Чутливий)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1685025660/products/pim/4066447256741-3651908/babylove-baby-waschgel-kopf-bis-fuss-sensitive', '500 мл', '2.45', '35', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Denkmit', 'Денкміт', '', 'Lufterfrischer Apfel & Kiwi', 'Освіжувач повітря (Яблуко та ківі)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1656693963/products/pim/4010355488671-2519399/denkmit-lufterfrischer-apfel-und-kiwi', '150 мл', '1.35', '35', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Denkmit', 'Денкміт', '', 'WC-Stein Blauspüler Flower', 'Туалетний блок', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1687772090/products/pim/4066447289336-3669507/denkmit-wc-blauspueler-flower', '2 шт', '1.15', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Frosch', 'Форш', '', 'Kalkreiniger Himbeer-Essig', 'Уксус для удаления накипи (Малиновая)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1663050649/products/pim/4001499961519-3453426/frosch-kalkreiniger-himbeer-essig', '500 мл', '2.25', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Frosch', 'Форш', '', 'Allzweckreiniger Soda', 'Универсальное чистящее средство, сода', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1663050649/products/pim/4001499961502-3453425/frosch-allzweckreiniger-soda', '500 мл', '2.25', '35', '10', '', '3']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Profissimo', 'Профіссімо', '', 'Schwammtücher', 'Губчасті серветки (Рушники, ганчірки)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1657806286/products/pim/4058172673450-2811833/profissimo-schwammtuecher', '5 шт', '0.95', '35', '10', '', '2']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Profissimo', 'Профіссімо', '', 'Topfschwämme', 'Губки', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1663744980/products/pim/4058172673412-2821817/profissimo-topfschwaemme', '6 шт', '0.95', '35', '10', '', '1']);
        db.run(`INSERT INTO products (brand_original, brand_translation, type, title_original, title_translation, image, volume, price, price_factor, amount, weight, 'exists') VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, ['Alverde NATURKOSMETIK', 'Алверде НАТУРКОСМЕТИК', '', 'Shampoo Sensitiv Bio-Echinacea, Bio-Jojoba', 'Шампунь, чутливий (Органічна ехінацея, жожоба)', 'https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1666006467/products/pim/4058172935848-3285619/alverde-naturkosmetik-shampoo-sensitiv-bio-echinacea-bio-jojoba', '200 мл', '2.25', '35', '10', '', '1']); */
    },
    admin: () => {
        const sqlite3 = require('sqlite3').verbose();
        const db = new sqlite3.Database('database.db');

        db.run(`UPDATE users SET admin = ? WHERE email = ?`, ['1', args[1]]);
    }
};

// Проверяем наличие функции для данного аргумента
if (argument in functions) {
    functions[argument]();
} else {
    console.log(`Неизвестный аргумент: ${argument}`);
}
